import Footer from "@/app/_components/footer";
import Navbar from "@/app/_components/navbar";
import Providers from "@/app/providers";
import { DynamicScreenDevTools } from "@/components/devtools/screen-devtools";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geist = Geist({ subsets: ["latin"], variable: "--font-geist" });
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Template Next.js - Tailwind CSS - TypeScript",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth antialiased selection:bg-neutral-300 dark:selection:bg-neutral-600"
      suppressHydrationWarning
    >
      <body
        className={cn(
          geist.variable,
          geistMono.variable,
          "isolate flex min-h-screen flex-col font-mono",
        )}
      >
        <Providers>
          <Navbar />
          {/* background effect */}
          <div className="fixed z-[-1] size-full">
            <div className="absolute h-full w-full animate-pulse bg-[radial-gradient(#ff000066_1px,transparent_1px)] [background-size:16px_16px] [mask-image:radial-gradient(ellipse_100%_100%_at_50%_0%,#000_30%,transparent_100%)]" />
          </div>

          <div className="isolate grid grow">{children}</div>
          <Footer />

          <DynamicScreenDevTools />
        </Providers>
      </body>
    </html>
  );
}
